## @file
# Azure Pipeline build file for a build using Windows and the latest Visual Studio toolchain supported.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: makubacki
      name: makubacki/mu_devops
      ref: install_wheel_setuptools_in_pip_install

variables:
- group: architectures-x86-64
- group: tool-chain-windows-visual-studio-latest

jobs:
- template: Matrix-Build-Job.yml
  parameters:
    arch_list: $(arch_list)
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
