name: Backport Commits to Release Branch

on:
  push:
    branches:
      - test_dev/202405

jobs:
  backport:
<<<<<<< HEAD
=======
    name: Backport Commits to Release Branch
>>>>>>> 4ac322ee6f (Directly use REST API to create the PR)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
<<<<<<< HEAD
      uses: actions/checkout@v3

    - name: Check if Backport is Requested
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          const label = context.payload.pull_request.labels.find(l => l.name === 'type:backport');
          if (!label) {
            console.log('Changes are not requested for backport. Exiting.');
            process.exit(0);
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Backport Info
      id: backport_info
      #run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
      uses: actions/github-script@v6
      with:
        script: |
          const core = require('@actions/core');
          const { context } = require('@actions/github');

          const ref = process.env.GITHUB_REF;
          const sourceBranchName = ref.replace('refs/heads/', '');
          const targetBranchName = sourceBranchName.replace('dev', 'test_release');
=======
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Determine Contribution Info
      id: backport_info
      uses: actions/github-script@v7
      with:
        script: |
          const BOLD = "\u001b[1m";

          const ref = process.env.GITHUB_REF;
          const sourceBranchName = ref.replace('refs/heads/', '');
          const targetBranchName = sourceBranchName.replace('dev', 'release');
>>>>>>> 4ac322ee6f (Directly use REST API to create the PR)

          const commits = context.payload.commits;
          const commitCount = commits.length;

<<<<<<< HEAD
          const commits = context.payload.commits.map(commit => commit.id);
          core.setOutput('commits', commits.join(' '));

          console.log(`Source branch name is ${sourceBranchName}`);
          console.log(`Target branch name is ${targetBranchName}`);
          console.log(`${commitCount} commits to backport:`);

          commits.forEach(commit => {
            console.log(`**SHA: ${commit.id}**`);
            console.log(`  >${commit.message}\n`);
          });

          core.setOutput('source_branch_name', sourceBranchName);
          core.setOutput('target_branch_name', targetBranchName);
          core.setOutput('commits', JSON.stringify(commits));
          core.setOutput('commit_by_id', commits.map(commit => commit.id).join(' '));
          core.setOutput('commit_messages', commits.map(commit => `**${commit.message.split('\n')[0]}**\n${commit.message.split('\n').slice(1).join('\n')}\n---`).join('\n')));
          core.setOutput('commit_count', commitCount);

    - name: Fetch ${{ steps.backport_info.outputs.source_branch_name }} Commits
      run: |
        git fetch origin ${{ steps.backport_info.outputs.source_branch_name }}
        git log main --pretty=format:"%H" -n ${{ steps.backport_info.outputs.commit_count }}

    - name: Checkout a Local ${{ steps.backport_info.outputs.target_branch_name }} Branch
      run: git checkout -b ${{ steps.backport_info.outputs.target_branch_name }} origin/${{ steps.backport_info.outputs.target_branch_name }}
=======
          console.log(`Source branch name is ${sourceBranchName}`);
          console.log(`Target branch name is ${targetBranchName}\n`);

          core.startGroup(`${commitCount} Commit(s) in this Contribution`);
          commits.forEach((commit, index) => {
            console.log(BOLD + `Commit #${index + 1}: ${commit.id}`);
            console.log(`  > ${commit.message}\n`);
          });
          core.endGroup();

          core.setOutput('source_branch_name', sourceBranchName);
          core.setOutput('target_branch_name', targetBranchName);
          core.setOutput('first_commit_id', commits[0].id);
          core.setOutput('commits', JSON.stringify(commits));
          core.setOutput('commit_by_id', commits.map(commit => commit.id).join(' '));
          core.setOutput('commit_messages', commits.map(commit => `${commit.message.split('\n')[0]}\n${commit.message.split('\n').slice(1).join('\n')}\n---`).join('\n'));
          core.setOutput('commit_count', commitCount);

    # - name: Get Associated Pull Request
    #   id: get_pr
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: GET /repos/${{ github.repository }}/commits/${{ steps.backport_info.outputs.first_commit_id }}/pulls
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   continue-on-error: true

    - name: Check if Backport is Requested
      uses: actions/github-script@v7
      with:
        script: |
          const BOLD = "\u001b[1m";
          const GREEN = "\u001b[32m";
          const MAGENTA = "\u001b[35m";

          const response = await github.request("GET /repos/${{ github.repository }}/commits/${{ steps.backport_info.outputs.first_commit_id }}/pulls", {
                  headers: {
                    authorization: `token ${process.env.GITHUB_TOKEN}`
                  }
                });

          //const prNumber = response.data.length > 0 ? response.data[0].number : null;

          // TEST
          const prNumber = "64";

          if (!prNumber) {
            console.log(GREEN + "No associated pull request found. Nothing to backport! Exiting.");
            process.exit(0);
          }

          console.log(`Associated Pull Request Number: ${prNumber}\n`);

          const { data: pull } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
            });

          core.startGroup(`${pull.labels.length} Label(s) in the PR`);
          pull.labels.forEach((label, index) => {
            console.log(BOLD + `Label #${index + 1}: \"${label.name}\"`);
            });
          core.endGroup();

          // TEST
          //const label = pull.labels.find(l => l.name === 'type:backport');
          const label = pull.labels.find(l => l.name === 'impact:non-functional');
          if (!label) {
            console.log(GREEN + "Changes are not requested for backport. Exiting.");
            process.exit(0);
          }

          console.log(MAGENTA + "The changes are requested for backport. Proceeding with backport.\n");

          core.setOutput("pr_number", prNumber);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch ${{ steps.backport_info.outputs.source_branch_name }} Commits (Source Branch)
      run: |
        git config --global user.email "mubot@microsoft.com"
        git config --global user.name "Project Mu Bot"
        git fetch origin ${{ steps.backport_info.outputs.source_branch_name }}
        git log origin/${{ steps.backport_info.outputs.source_branch_name }} --pretty=format:"%H" -n ${{ steps.backport_info.outputs.commit_count }}

    - name: Checkout a Local ${{ steps.backport_info.outputs.target_branch_name }} Branch (Destination Branch)
      run: |
        git fetch origin ${{ steps.backport_info.outputs.target_branch_name }}
        git checkout -b ${{ steps.backport_info.outputs.target_branch_name }} origin/${{ steps.backport_info.outputs.target_branch_name }}
>>>>>>> 4ac322ee6f (Directly use REST API to create the PR)

    - name: Check for Merge Conflicts
      id: merge_conflicts
      run: |
<<<<<<< HEAD
        for commit in ${{ steps.backport_info.outputs.commit_by_id }}; do
          git cherry-pick $commit || exit 1
        done
      continue-on-error: true

    - name: Push to ${{ steps.backport_info.outputs.target_branch_name }} if No Conflicts
      if: success()
      run: |
        git push origin ${{ steps.backport_info.outputs.target_branch_name }}

    - name: Create pull request if conflicts
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const core = require('@actions/core');
          const { context, getOctokit } = require('@actions/github');

          const token = core.getInput('GITHUB_TOKEN');
          const octokit = getOctokit(token);

          const { owner, repo } = context.repo;

          const commitMessages = core.getOutput('commit_messages');
          const prBranch = core.getOutput('target_branch_name');
          const pullRequest = await octokit.pulls.create({
            owner,
            repo,
            title: "Release Branch Manual Merge Conflict Resolution Needed",
            head: 'conflict-resolution',
            base: '${prBranch}',
            body: `The following commits need manual resolution:\n\n${commitMessages}`,
          });

          console.log(`Pull request created: ${pullRequest.data.html_url}`);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
        conflict=false
        for commit in ${{ steps.backport_info.outputs.commit_by_id }}; do
          git cherry-pick $commit || {
            conflict=true;
            echo -e "\nMerge conflict detected for commit $commit! Committing it with conflict markers.";
            original_author=$(git log -1 --pretty=format:'%an <%ae>' $commit)
            original_date=$(git log -1 --pretty=format:'%ad' --date=iso-strict $commit)
            original_message=$(git log -1 --pretty=%B $commit)
            git add -A
            GIT_COMMITTER_DATE="$original_date" GIT_AUTHOR_DATE="$original_date" git commit --author="$original_author" -m "[CONFLICT] $original_message"
          }
        done
        echo "merge_conflict=$conflict" >> $GITHUB_ENV
      continue-on-error: true

    - name: Push to ${{ steps.backport_info.outputs.target_branch_name }} if No Conflicts
      if: env.merge_conflict == 'false'
      run: |
        git push origin ${{ steps.backport_info.outputs.target_branch_name }}:${{ steps.backport_info.outputs.target_branch_name }}

    - name: Generate a Unique PR Branch Name (On Merge Conflict)
      if: env.merge_conflict == 'true'
      id: merge_conflict_branch_info
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        branch_name="merge-conflict/${{ steps.backport_info.outputs.target_branch_name }}/$TIMESTAMP"
        echo -e "\nMerge conflict branch name generated: $branch_name"

        git branch -m $branch_name
        git push origin refs/heads/$branch_name:refs/heads/$branch_name
        # Temporarily check the commits at the tip of the branch
        git log -5
        echo "{branch_name}={$branch_name}" >> $GITHUB_OUTPUT

    - name: Create Pull Request (On Merge Conflict)
      if: env.merge_conflict == 'true'
      run: |
          PR_BRANCH="refs/remotes/origin/${{ steps.merge_conflict_branch_info.outputs.branch_name }}"
          BASE_BRANCH="refs/remotes/origin/${{ steps.backport_info.outputs.target_branch_name }}"
          PR_TITLE="Manual Merge Conflict Resolution for ${{ steps.backport_info.outputs.first_commit_id }} Commits into ${{ steps.backport_info.outputs.target_branch_name }}"
          PR_BODY="This pull request is created to resolve the merge conflict that occurred while backporting the commits from ${{ steps.backport_info.outputs.source_branch_name }} to ${{ steps.backport_info.outputs.target_branch_name }}."

          # Create the pull request with the REST API
          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/pulls \
          -H "Authorization: token $PUSH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$PR_BRANCH\",\"base\":\"$BASE_BRANCH\"}"
      env:
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
>>>>>>> 4ac322ee6f (Directly use REST API to create the PR)
