# A workflow to build EDKII packages using the CLANGPDB toolchain in windows and ubuntu environments.
#
# NOTE: This file is automatically synchronized from Mu DevOps to keep the version of the
#       workflow up to date. Update the original file there instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# NOTE: Because this pipeline YAML file is a Nunjucks template, the pipeline syntax of `{{}}` will conflict with
#       Nunjucks style. Surround pipeline YAML code that uses `{{}}` within `raw` and `endraw` tags
#       to allow it to pass through Nunjucks processing.

name: CLANGPDB Package CI

on:
  workflow_dispatch:
  push:
    branches:
      - only_run_pr_val_on_default_branch_test
  pull_request:
    branches:
      - only_run_pr_val_on_default_branch_test

concurrency:
  group: clangpdb-package-ci-${{ github.ref }}

  cancel-in-progress: true

jobs:
  noop:
    name: No-op
    runs-on: ubuntu-latest

    steps:
      - name: Succeed without running CI
        run: exit 0

